const texts = [
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Eu mi bibendum neque egestas. Sed augue lacus viverra vitae congue. Enim facilisis gravida neque convallis a cras. Faucibus scelerisque eleifend donec pretium. Aliquam malesuada bibendum arcu vitae. Aliquam id diam maecenas ultricies mi eget mauris pharetra. Amet commodo nulla facilisi nullam vehicula ipsum a arcu. Arcu non odio euismod lacinia. Volutpat lacus laoreet non curabitur.",
  "Sed libero enim sed faucibus turpis in eu mi. Nunc faucibus a pellentesque sit amet porttitor. Justo laoreet sit amet cursus sit amet dictum sit amet. Facilisis leo vel fringilla est ullamcorper eget nulla. Non odio euismod lacinia at quis risus sed. Erat imperdiet sed euismod nisi porta. Amet dictum sit amet justo donec. Nunc id cursus metus aliquam eleifend. Facilisi cras fermentum odio eu feugiat pretium. Risus viverra adipiscing at in tellus integer. Habitant morbi tristique senectus et netus et malesuada. Tincidunt tortor aliquam nulla facilisi cras fermentum odio. Proin sagittis nisl rhoncus mattis rhoncus urna neque viverra. Enim sed faucibus turpis in eu mi bibendum neque. Massa massa ultricies mi quis hendrerit dolor.",
  "Cras sed felis eget velit aliquet sagittis id. Sed augue lacus viverra vitae congue eu consequat ac felis. Egestas purus viverra accumsan in nisl nisi scelerisque. Id diam maecenas ultricies mi eget. Diam phasellus vestibulum lorem sed risus ultricies tristique nulla. Risus sed vulputate odio ut enim blandit volutpat maecenas volutpat. Malesuada fames ac turpis egestas. Mauris ultrices eros in cursus turpis massa tincidunt dui ut. Consequat mauris nunc congue nisi. Massa sed elementum tempus egestas sed sed risus pretium quam. Scelerisque mauris pellentesque pulvinar pellentesque habitant morbi. Tortor posuere ac ut consequat semper viverra nam libero. Maecenas ultricies mi eget mauris pharetra et ultrices.",
  "Tempus egestas sed sed risus pretium quam vulputate. Mattis nunc sed blandit libero volutpat sed cras ornare arcu. Sed lectus vestibulum mattis ullamcorper velit sed. Duis convallis convallis tellus id. Amet cursus sit amet dictum sit amet. Eu scelerisque felis imperdiet proin fermentum leo vel orci. Et malesuada fames ac turpis. Nunc sed augue lacus viverra vitae. Malesuada pellentesque elit eget gravida cum sociis natoque penatibus et. Ut faucibus pulvinar elementum integer enim neque volutpat ac. Vivamus arcu felis bibendum ut tristique et egestas. Purus sit amet volutpat consequat mauris nunc congue nisi vitae. Ut aliquam purus sit amet luctus. Suspendisse interdum consectetur libero id faucibus nisl tincidunt. Molestie ac feugiat sed lectus vestibulum. Vitae justo eget magna fermentum iaculis eu non. Lorem mollis aliquam ut porttitor leo a diam sollicitudin. Lorem ipsum dolor sit amet consectetur adipiscing elit.",
  "Vel turpis nunc eget lorem dolor sed viverra ipsum. Sit amet nisl purus in mollis nunc sed id. Tempus egestas sed sed risus pretium quam. Nec dui nunc mattis enim. Nunc id cursus metus aliquam. Et tortor consequat id porta nibh venenatis. Posuere urna nec tincidunt praesent semper feugiat. Risus nec feugiat in fermentum posuere. Aenean euismod elementum nisi quis eleifend quam. Volutpat consequat mauris nunc congue nisi vitae suscipit tellus mauris. Vestibulum mattis ullamcorper velit sed. Nam libero justo laoreet sit amet cursus. Est placerat in egestas erat imperdiet sed euismod. Quis blandit turpis cursus in hac.",
  "Cursus mattis molestie a iaculis at erat pellentesque. Vulputate mi sit amet mauris commodo quis imperdiet massa. Ullamcorper a lacus vestibulum sed arcu non odio euismod. Lectus sit amet est placerat in egestas erat. Odio ut sem nulla pharetra diam sit. Eget nulla facilisi etiam dignissim diam. Consequat interdum varius sit amet mattis vulputate enim nulla. Nisi porta lorem mollis aliquam ut porttitor leo. Fringilla phasellus faucibus scelerisque eleifend donec pretium vulputate. Rhoncus urna neque viverra justo nec ultrices dui sapien eget. Ullamcorper a lacus vestibulum sed. Adipiscing enim eu turpis egestas. Eget lorem dolor sed viverra ipsum nunc.",
  "Dignissim enim sit amet venenatis urna cursus eget. Ullamcorper sit amet risus nullam eget felis. Molestie at elementum eu facilisis sed odio. Turpis massa sed elementum tempus egestas. Massa sed elementum tempus egestas sed sed risus pretium. Nisl tincidunt eget nullam non. Proin sed libero enim sed faucibus turpis in eu mi. Ut sem viverra aliquet eget sit amet tellus. Turpis in eu mi bibendum neque. Tempus imperdiet nulla malesuada pellentesque elit eget gravida cum.",
  "Vel facilisis volutpat est velit egestas. Eu consequat ac felis donec et odio. Porta nibh venenatis cras sed felis eget velit. Sit amet consectetur adipiscing elit ut aliquam. Sed cras ornare arcu dui vivamus. Ullamcorper eget nulla facilisi etiam. Et malesuada fames ac turpis egestas sed tempus urna. Nullam non nisi est sit amet facilisis. Ut sem nulla pharetra diam sit amet. Eu augue ut lectus arcu bibendum at varius vel. Eu consequat ac felis donec et odio pellentesque diam. Ut diam quam nulla porttitor massa id neque. Odio aenean sed adipiscing diam donec. Tincidunt praesent semper feugiat nibh sed pulvinar proin gravida hendrerit. Malesuada proin libero nunc consequat interdum varius sit amet.",
  "At consectetur lorem donec massa sapien faucibus et molestie ac. Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Nisl purus in mollis nunc sed id semper risus. Gravida dictum fusce ut placerat orci nulla pellentesque dignissim. Interdum posuere lorem ipsum dolor. Quam nulla porttitor massa id neque aliquam. Ut faucibus pulvinar elementum integer enim neque. Ut tortor pretium viverra suspendisse. Sem fringilla ut morbi tincidunt augue interdum. Et leo duis ut diam quam nulla porttitor massa id.",
  "Iaculis eu non diam phasellus vestibulum lorem. Rhoncus urna neque viverra justo. Pellentesque habitant morbi tristique senectus et. Eget arcu dictum varius duis at consectetur. Sed egestas egestas fringilla phasellus faucibus. Nullam ac tortor vitae purus faucibus ornare suspendisse sed nisi. Risus quis varius quam quisque id diam vel quam elementum. Lacus sed turpis tincidunt id aliquet risus feugiat in. Lectus sit amet est placerat in egestas. Blandit libero volutpat sed cras ornare arcu. Purus gravida quis blandit turpis cursus in hac habitasse. Fermentum dui faucibus in ornare quam viverra. Enim blandit volutpat maecenas volutpat blandit. Dis parturient montes nascetur ridiculus mus mauris. Pharetra magna ac placerat vestibulum.",
];

const generateText = (numberOfParagraphs) => {
  let generatedText = "";

  for (let x = 0; x < numberOfParagraphs; x++) {
    const position = Math.floor(Math.random() * texts.length);
    if (x === numberOfParagraphs - 1) {
      generatedText += texts[position];
    } else {
      generatedText += texts[position] + "\n";
    }
  }

  return generatedText;
};

module.exports = {
  generateText,
};
